# https://github.com/docker-library/docs/blob/master/postgres/README.md
# https://www.docker.com/blog/how-to-use-the-postgres-docker-official-image/
# https://github.com/docker/awesome-compose/tree/master/official-documentation-samples/django/

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d db-1" ]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - networkZ

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - networkZ

networks:
  networkZ:

volumes:
  pgdata: