# Generated by Django 5.1.4 on 2024-12-07 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='company',
            table='Company',
        ),
        migrations.AlterModelTable(
            name='document',
            table='Document',
        ),
        migrations.AlterModelTable(
            name='signers',
            table='Signers',
        ),
    ]
